### ISSUE TITLE
Login app - Change the basic style

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/sso-template#6]
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=831%3A0&t=jdUBSTjC1zu0f0ws-0

**Comment by VanTrieuThanh** [comment]
Design: align text, missing icon, border color, background color . color button 
![image](https://user-images.githubusercontent.com/44457418/224003270-22661312-2212-4e16-abfb-19dabdfba030.png)
on site 
![Screenshot from 2023-03-09 17-51-19](https://user-images.githubusercontent.com/44457418/224002370-25dbac83-7f4b-4a88-a041-494bcdb4b9da.png)
